### ISSUE TITLE
Unable to New Credit Card / Make Payment

### ISSUE THREAD

**Issue by pheinrichs** [SonarSoftware/customer_portal#5]
When attempting to make a new credit card and submit a payment. I received this error in the log file 

---
Next ErrorException: Undefined property: Illuminate\Http\RedirectResponse::$transaction_id (View: /var/www/html/customer_portal/portal/resources/views/pages/billing/payment_success.blade.php) in /var/www/html/customer_portal/portal/storage/framework/views/dba4c3d76a20e25ec5dc359c3e84bc4a0687e4be.php:13

----
Or the logs would just respond

[2017-06-08 15:05:22] production.ERROR: There was an error submitting the payment. Please check and try again
---

Install is on a centos 6.7 install.
The following are installed 
php-json php-pgsql php-curl php-mbstring php-bcmath php-zip php-gmp php-xml php-sqlite3 

Any idea what I would need to do to resolve?

**Comment by SonarSoftware** [comment]
Hi,

Not without more information, have you changed anything else? We'd probably need to access your customer portal to troubleshoot this further, if you haven't changed any of the code. Please contact support@sonar.software with the details.

**Comment by pheinrichs** [comment]
API user didn't have correct permissions.
